export default {
    MERCHANDISE_LIST: {
        REQUEST: 'MERCHANDISE_LIST__REQUEST',
        SUCCESS: 'MERCHANDISE_LIST__SUCCESS',
        FALIURE: 'MERCHANDISE_LIST__FALIURE',
    },
    USER: {
        REQUEST: 'USER__REQUEST',
        SUCCESS: 'USER__SUCCESS',
        FALIURE: 'USER__FALIURE',
        USER_INFO: {
            SET: 'USER__USER_INFO__SET'
        }
    },
    CHECK_PASS_CODE: {
        REQUEST: 'CHECK_PASS_CODE__REQUEST',
        SUCCESS: 'CHECK_PASS_CODE__SUCCESS',
        FALIURE: 'CHECK_PASS_CODE__FALIURE',
    },
    CONFIGS: {
        AIESEC_FUNCTIONS: {
            REQUEST: 'CONFIGS__AIESEC_FUNCTIONS__REQUEST',
            SUCCESS: 'CONFIGS__AIESEC_FUNCTIONS__SUCCESS',
            FALIURE: 'CONFIGS__AIESEC_FUNCTIONS__FALIURE',
        },
        AIESEC_ROLES: {
            REQUEST: 'CONFIGS__AIESEC_ROLES__REQUEST',
            SUCCESS: 'CONFIGS__AIESEC_ROLES__SUCCESS',
            FALIURE: 'CONFIGS__AIESEC_ROLES__FALIURE',
        },
    }
}