export default {
    MERCHANDISE_LIST: {
        REQUEST: 'MERCHANDISE_LIST__REQUEST',
        SUCCESS: 'MERCHANDISE_LIST__SUCCESS',
        FALIURE: 'MERCHANDISE_LIST__FALIURE',
    },
    USER: {
        REQUEST: 'USER__REQUEST',
        SUCCESS: 'USER__SUCCESS',
        FALIURE: 'USER__FALIURE',
    },
    CHECK_PASS_CODE: {
        REQUEST: 'CHECK_PASS_CODE__REQUEST',
        SUCCESS: 'CHECK_PASS_CODE__SUCCESS',
        FALIURE: 'CHECK_PASS_CODE__FALIURE',
    },
}