export default {
    MERCHANDISE_LIST: {
        REQUEST: 'MERCHANDISE_LIST__REQUEST',
        SUCCESS: 'MERCHANDISE_LIST__SUCCESS',
        FALIURE: 'MERCHANDISE_LIST__FALIURE',
    },
    USER_MERCHANDISE: {
        SET: 'USER_MERCHANDISE_SET',
        REQUEST: 'USER_MERCHANDISE__REQUEST',
        SUCCESS: 'USER_MERCHANDISE__SUCCESS',
        FALIURE: 'USER_MERCHANDISE__FALIURE',
    },
    USER: {
        REQUEST: 'USER__REQUEST',
        SUCCESS: 'USER__SUCCESS',
        FALIURE: 'USER__FALIURE',
        USER_INFO: {
            SET: 'USER__USER_INFO__SET'
        }
    },
    CHECK_PASS_CODE: {
        REQUEST: 'CHECK_PASS_CODE__REQUEST',
        SUCCESS: 'CHECK_PASS_CODE__SUCCESS',
        FALIURE: 'CHECK_PASS_CODE__FALIURE',
    },
    CONFIGS: {
        AIESEC_FUNCTIONS: {
            REQUEST: 'CONFIGS__AIESEC_FUNCTIONS__REQUEST',
            SUCCESS: 'CONFIGS__AIESEC_FUNCTIONS__SUCCESS',
            FALIURE: 'CONFIGS__AIESEC_FUNCTIONS__FALIURE',
        },
        AIESEC_ROLES: {
            REQUEST: 'CONFIGS__AIESEC_ROLES__REQUEST',
            SUCCESS: 'CONFIGS__AIESEC_ROLES__SUCCESS',
            FALIURE: 'CONFIGS__AIESEC_ROLES__FALIURE',
        },
        TOGGOLE: {
            IS_USER_INFO_STEP_VALID: "CONFIGS__TOGGOLE__IS_USER_INFO_STEP_VALID",
            IS_USER_ID_PHOTOS_VALID: "CONFIGS__TOGGOLE__IS_USER_ID_PHOTOS_VALID",
            IS_MERCHANDISE_SELECTOR_VALID: "CONFIGS__TOGGOLE__IS_MERCHANDISE_SELECTOR_VALID",
        }
    }
}